#include <stdlib.h>
#include <time.h>
#include <math.h>
#include <string.h>
#include <stdio.h>
#include "mmm.h"

/**
 * Allocate and initialize the matrices on the heap. Populate
 * the input matrices with random integers from 0 to 99
 */
void mmm_init()
{
	// Malloc first matrix (A)
	A = (double **)malloc(sizeof(double *) * size);
	for (int i = 0; i < size; i++)
	{
		A[i] = (double *)malloc(sizeof(double) * size);
	}

	// TODO - Populate A with random double values 0-99
	for (int i = 0; i < size; i++)
	{
		for (int j = 0; j < size; j++)
		{
			A[i][j] = rand() % 100;
		}
	}

	// Malloc second matrix (B)
	B = (double **)malloc(sizeof(double *) * size);
	for (int i = 0; i < size; i++)
	{
		B[i] = (double *)malloc(sizeof(double) * size);
	}

	// TODO - Populate B with random double values 0-99
	for (int i = 0; i < size; i++)
	{
		for (int j = 0; j < size; j++)
		{
			B[i][j] = rand() % 100;
		}
	}

	// Malloc third matrix (C)
	C = (double **)malloc(sizeof(double *) * size);
	for (int i = 0; i < size; i++)
	{
		C[i] = (double *)malloc(sizeof(double) * size);
	}

	// Malloc third matrix (D)
	D = (double **)malloc(sizeof(double *) * size);
	for (int i = 0; i < size; i++)
	{
		D[i] = (double *)malloc(sizeof(double) * size);
	}
}

/**
 * Reset a given matrix to zeroes
 * @param matrix pointer to a 2D array
 */
void mmm_reset(double **matrix)
{
	// TODO
	for (int i = 0; i < size; i++)
	{
		for (int j = 0; j < size; j++)
		{
			matrix[i][j] = 0;
		}
	}
}

/**
 * Free up memory allocated to all matrices
 */
void mmm_freeup()
{
	// Free matrix A
	for (int i = 0; i < size; i++)
	{
		free(A[i]);
		A[i] = NULL;
	}

	free(A);
	A = NULL;

	// Free matrix B
	for (int i = 0; i < size; i++)
	{
		free(B[i]);
		B[i] = NULL;
	}

	free(B);
	B = NULL;

	// Free matrix C
	for (int i = 0; i < size; i++)
	{
		free(C[i]);
		C[i] = NULL;
	}

	free(C);
	C = NULL;

	// Free matrix D
	for (int i = 0; i < size; i++)
	{
		free(D[i]);
		D[i] = NULL;
	}

	free(D);
	D = NULL;
}

/**
 * Sequential MMM
 */
void mmm_seq()
{
	// Based on algorithm showed at https://www.geeksforgeeks.org/c-program-multiply-two-matrices/
	for (int i = 0; i < size; i++)
	{
		for (int j = 0; j < size; j++)
		{
			C[i][j] = 0;
			for (int k = 0; k < size; k++)
			{
				C[i][j] += A[i][k] * B[k][j];
			}
		}
	}
}

/**
 * Parallel MMM
 */
void *mmm_par(void *args)
{
	// TODO - code to perform parallel MMM
	thread_args *params = (thread_args *)args;

	for (int i = params->begin; i < params->end; i++)
	{
		for (int j = params->begin; j < params->end; j++)
		{
			D[i][j] = 0;
			for (int k = 0; k < size; k++)
			{
				D[i][j] += A[i][k] * B[k][j];
			}
		}
	}
}

/**
 * Verifies the correctness between the matrices generated by
 * the sequential run and the parallel run.
 *
 * @return the largest error between two corresponding elements
 * in the result matrices
 */
double mmm_verify()
{
	// TODO
	return -1;
}
